kc- added new job to update ALL subjects over a RANGE of quarters
ucsb-cs156-f22/f22-6pm-courses pull request #54
Opened 2022-11-30 10:53 UTC by khangvchung

Added new job that builds on #21 to get all subjects over a range of quarters.

Files modified: JobsController.java, JobsControllerTests.java

Files added: UpdateCourseDataRangeOfQuartersJob.java, UpdateCourseDataRangeOfQuartersJobFactory.java, UpdateCourseDataRangeOfQuartersJobTests.java, UpdateCourseDataRangeOfQuartersJobFactoryTests.java

This can be tested under the jobs-controller updateCoursesRangeOfQuarters

<img width="1397" alt="Screen Shot 2022-11-30 at 2 49 02 AM" src="https://user-images.githubusercontent.com/77039901/204776850-f73ae0eb-0f96-415d-9688-575c4e3588a8.png">

After executing, you can go under the admin tab and manage jobs to see a screen like this that will continue to list all subjects over a range of quarters.

<img width="1204" alt="Screen Shot 2022-11-30 at 2 51 46 AM" src="https://user-images.githubusercontent.com/77039901/204777372-c6f4a343-b6f8-4745-9df9-82608540b890.png">

Passed all tests locally, however have small issues with the factory tests and getting an empty subject when attempting to test, leading to lower code coverage.

<img width="1162" alt="Screen Shot 2022-11-30 at 2 53 28 AM" src="https://user-images.githubusercontent.com/77039901/204777716-bef7b326-dd90-44d2-ac70-c8d8d1e2f015.png">

2022-11-30 17:25 UTC, pconrad commented
For the CI/CD failures, see this thread on the team slack.  I think it may help you fix the problem:

https://ucsb-cs156-f22.slack.com/archives/C043AUN4R9B/p1669791453331639

2022-12-01 03:01 UTC, pikarap1234 submitted a review, later dismissed
LGTM - Shoutout to TAs for merge help

2022-12-04 22:15 UTC, pconrad requested changes
Please know that it is considered unprofessional to submit a PR with commented out code in it, unless the commented out code is REALLY, REALLY, needed for a very specific reason, and you make a case to the team why it REALLY, REALLY, needs to be kept.

2022-12-04 22:15 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataRangeOfQuartersJob.java
> +        }
Tell me more about this code.. 

Also why do we still have commented out code in code that's intended to be merged?

2022-12-04 22:15 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataRangeOfQuartersJob.java
> +                //current_qtr++;
Please remove commented out lines

2022-12-04 22:15 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataRangeOfQuartersJob.java
> +                    //current_year++;
Please remove commented one lines.

2022-12-05 00:45 UTC, pconrad requested changes
Please see my notes on a way to structure this code that is much easier.

2022-12-05 06:56 UTC, pconrad approved these changes
LGTM!

2022-12-05 07:12 UTC, pconrad approved these changes
LGTM

2022-12-07 02:54 UTC, merged